#!/usr/bin/env python

import os
import shutil
import torch
from diffusers.pipelines.stable_diffusion.safety_checker import (
    StableDiffusionSafetyChecker,
)
from transformers import CLIPFeatureExtractor


MODEL_CACHE = "diffusers-cache"
SAFETY_MODEL_ID = "CompVis/stable-diffusion-safety-checker"

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

saftey_checker = StableDiffusionSafetyChecker.from_pretrained(
    SAFETY_MODEL_ID,
    torch_dtype=torch.float16,
)
saftey_checker.save_pretrained(MODEL_CACHE + "/stable-diffusion-safety-checker")

cfe = CLIPFeatureExtractor.from_pretrained(
    "openai/clip-vit-base-patch32"
)
cfe.save_pretrained(MODEL_CACHE + "/clip-vit-base-patch32")

